# ===============================
# CONEXIÓN DIRECTA A BASE DE DATOS (PUERTO 5432)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.olxldsfzyixhwivznemo
spring.datasource.password=6H3fP@eBN/Hd!.n
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=file:uploads/,classpath:/static/
# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Supabase Storage Config# Supabase Storage Config
supabase.url=https://olxldsfzyixhwivznemo.supabase.co
supabase.key=${SUPABASE_KEY}
supabase.bucket=productos