# ===============================
# CONEXIÓN DIRECTA A BASE DE DATOS (PUERTO 5432)
# ===============================
spring.datasource.url=jdbc:postgresql://db.olxldsfzyixhwivznemo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=6H3fP@eBN/Hd!.n
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=file:uploads/,classpath:/static/
# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true